---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.20.3

platforms:
  - name: debian-7
    driver_config:
      box: debian/wheezy64
  - name: debian-8
    driver_config:
      box: debian/jessie64
  - name: debian-9
    driver_config:
      box: debian/stretch64

suites:
- name: default
  run_list:
  - recipe[debian::default]
  attributes:
    debian:
      deb_src: true
      security_mirror: http://ftp.nl.debian.org/debian-security
